services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/havilah
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_DB_NAME: havilah_edtech_content
      SECRET_KEY: change-me
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: havilah
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
